# Generated by Django 2.2.12 on 2020-04-15 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the object type",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_plural",
                    models.CharField(
                        help_text="Plural name of the object type",
                        max_length=100,
                        verbose_name="name plural",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.SmallIntegerField(
                        help_text="Integer version of the OBJECTTYPE",
                        verbose_name="version",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        auto_now=True,
                        help_text="Date of Version publication",
                        verbose_name="publication date",
                    ),
                ),
                (
                    "json_schema",
                    models.URLField(
                        help_text="Url reference to JSON schema for Object validation",
                        verbose_name="JSON schema",
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="api.ObjectType",
                    ),
                ),
            ],
            options={"unique_together": {("object_type", "version")},},
        ),
    ]
