# Generated by Django 2.2.12 on 2020-08-26 17:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20200824_1843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectversion",
            name="json_schema",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default={},
                help_text="JSON schema for Object validation",
                verbose_name="JSON schema",
            ),
        ),
    ]
