# Generated by Django 2.2.24 on 2021-11-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        help_text="Access token for GitHub authorization. Required for exporting. Can be generated at https://github.com/settings/tokens",
                        max_length=250,
                        verbose_name="token",
                    ),
                ),
                (
                    "repo",
                    models.CharField(
                        help_text="GitHub repository in the format {owner}/{name}",
                        max_length=250,
                        verbose_name="repo",
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        blank=True,
                        help_text="Path to the folder in the repository for import/export. If empty the root folder is used.",
                        max_length=250,
                        verbose_name="folder",
                    ),
                ),
                (
                    "only_json",
                    models.BooleanField(
                        default=True,
                        help_text="Show only .json files as import options",
                        verbose_name="only JSON",
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub configuration",
            },
        ),
    ]
