# Generated by Django 2.2.12 on 2020-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectversion",
            name="version",
            field=models.PositiveSmallIntegerField(
                help_text="Integer version of the OBJECTTYPE", verbose_name="version"
            ),
        ),
    ]
