# Generated by Django 2.2.12 on 2020-08-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20200518_1729"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttype",
            name="contact",
            field=models.CharField(
                blank=True,
                help_text="Person in the organization who can provide information about the object type",
                max_length=200,
                verbose_name="contact",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="The description of the object type",
                max_length=1000,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="domain",
            field=models.CharField(
                blank=True,
                help_text="Business department which is responsible for the object type",
                max_length=200,
                verbose_name="domain",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="maintainer",
            field=models.CharField(
                blank=True,
                help_text="Organization which is responsible for the object type",
                max_length=200,
                verbose_name="maintainer",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="public",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this data is accessible without any specific authorizations",
                verbose_name="public",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("deprecated", "Deprecated"),
                ],
                default="draft",
                help_text="Status of the object type",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
