# Generated by Django 2.2.12 on 2020-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200821_1638"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objecttype",
            name="status",
        ),
        migrations.AddField(
            model_name="objectversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("deprecated", "Deprecated"),
                ],
                default="draft",
                help_text="Status of the object type version",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
