# Generated by Django 2.2.12 on 2020-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20200902_1703"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objecttype",
            name="maintainer_contact_email",
            field=models.CharField(
                blank=True,
                help_text="Person in the organization who can provide information about the object type",
                max_length=200,
                verbose_name="maintainer contact email",
            ),
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="maintainer_organization",
            field=models.CharField(
                blank=True,
                help_text="Organization which is responsible for the object type",
                max_length=200,
                verbose_name="maintainer organization",
            ),
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="public_data",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether this data is accessible without any specific authorizations",
                verbose_name="public data",
            ),
        ),
    ]
