# Generated by Django 2.2.12 on 2020-09-01 13:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_auto_20200824_1843"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectversion",
            name="json_schema",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                help_text="JSON schema for Object validation",
                verbose_name="JSON schema",
            ),
        ),
        migrations.AlterField(
            model_name="objectversion",
            name="version",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Integer version of the OBJECTTYPE",
                verbose_name="version",
            ),
        ),
    ]
