# Generated by Django 2.2.12 on 2020-11-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20200901_1550"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objecttype", old_name="domain", new_name="maintainer_department"
        ),
        migrations.RenameField(
            model_name="objecttype",
            old_name="maintainer_contact_email",
            new_name="contact_email",
        ),
    ]
