# Generated by Django 2.2.12 on 2020-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20201111_1649"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objecttype",
            name="public_data",
        ),
        migrations.AddField(
            model_name="objecttype",
            name="data_classification",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("intern", "Intern"),
                    ("confidential", "Confidential"),
                    ("strictly_confidential", "Strictly confidential"),
                ],
                default="open",
                help_text="Confidential level of the object type",
                max_length=20,
                verbose_name="data classification",
            ),
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="contact_email",
            field=models.CharField(
                blank=True,
                help_text="Email of the person in the organization who can provide information about the object type",
                max_length=200,
                verbose_name="contact email",
            ),
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="maintainer_department",
            field=models.CharField(
                blank=True,
                help_text="Business department which is responsible for the object type",
                max_length=200,
                verbose_name="maintainer department",
            ),
        ),
    ]
