# Generated by Django 2.2.12 on 2020-11-11 16:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_auto_20201111_1707"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttype",
            name="contact_person",
            field=models.CharField(
                blank=True,
                help_text="Name of the person in the organization who can provide information about the object type",
                max_length=200,
                verbose_name="contact person",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="documentation_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the documentation for the object type",
                verbose_name="documentation url",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="labels",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                help_text="Key-value pairs of keywords related for the object type",
                verbose_name="labels",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="provider_organization",
            field=models.CharField(
                blank=True,
                help_text="Organization which is responsible for publication of the object type",
                max_length=200,
                verbose_name="provider organization",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Name of the system from which the object type originates",
                max_length=200,
                verbose_name="source",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="update_frequency",
            field=models.CharField(
                choices=[
                    ("real_time", "Real-time"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Indicates how often the object type is updated",
                max_length=10,
                verbose_name="update frequency",
            ),
        ),
    ]
