# Generated by Django 2.2.12 on 2020-11-12 10:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_auto_20201111_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objecttype",
            name="labels",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text="Key-value pairs of keywords related for the object type",
                verbose_name="labels",
            ),
        ),
    ]
