# Generated by Django 2.2.12 on 2020-11-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_auto_20201112_1123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectversion",
            name="version",
            field=models.PositiveSmallIntegerField(
                help_text="Integer version of the OBJECTTYPE", verbose_name="version"
            ),
        ),
    ]
