# Generated by Django 2.2.12 on 2020-11-26 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20201118_1251"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objectversion",
            old_name="publication_date",
            new_name="created_at",
        ),
    ]
