# Generated by Django 2.2.12 on 2020-11-26 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_auto_20201126_1952"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttype",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date when the object type was created",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objecttype",
            name="modified_at",
            field=models.DateField(
                auto_now=True,
                help_text="Last date when the object type was modified",
                verbose_name="modified at",
            ),
        ),
        migrations.AddField(
            model_name="objectversion",
            name="modified_at",
            field=models.DateField(
                auto_now=True,
                help_text="Last date when the version was modified",
                verbose_name="modified at",
            ),
        ),
        migrations.AddField(
            model_name="objectversion",
            name="published_at",
            field=models.DateField(
                help_text="Date when the version was published",
                null=True,
                blank=True,
                verbose_name="published_at",
            ),
        ),
        migrations.AlterField(
            model_name="objectversion",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Date when the version was created",
                verbose_name="created at",
            ),
        ),
    ]
