# Generated by Django 3.2.17 on 2023-02-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_auto_20211203_1225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objecttype",
            name="data_classification",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("intern", "Intern"),
                    ("confidential", "Confidential"),
                    ("strictly_confidential", "Strictly confidential"),
                ],
                default="open",
                help_text="Confidential level of the object type",
                max_length=50,
                verbose_name="data classification",
            ),
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="labels",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Key-value pairs of keywords related for the object type",
                verbose_name="labels",
            ),
        ),
        migrations.AlterField(
            model_name="objectversion",
            name="json_schema",
            field=models.JSONField(
                default=dict,
                help_text="JSON schema for Object validation",
                verbose_name="JSON schema",
            ),
        ),
    ]
