# Generated by Django 5.2.7 on 2025-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_auto_20230207_1401"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttype",
            name="linkable_to_zaken",
            field=models.BooleanField(
                default=False,
                help_text="Objects of this type can have a link to 1 or more Zaken.\nTrue indicates the lifetime of the object is linked to the lifetime of linked zaken, i.e., when all linked Zaken to an object are archived/destroyed, the object will also be archived/destroyed.",
                verbose_name="linkable to zaken",
            ),
        ),
    ]
