# Generated by Django 4.2.11 on 2024-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token", "0007_delete_oldtokenauth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenauth",
            name="token",
            field=models.CharField(max_length=40, unique=True, verbose_name="token"),
        ),
    ]
