name: generate-sdks

on:
  push:
    paths:
      - "src/objecttypes/api/v*/openapi.yaml"
      - ".github/workflows/generate-sdks.yml"
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-generate-sdks:
    uses: maykinmedia/open-api-workflows/.github/workflows/generate-sdks.yml@v1
    strategy:
      matrix:
        version:
          - v1
          - v2
    with:
      node-version: '18'
      schema-path: 'src/objecttypes/api/${{ matrix.version }}/openapi.yaml'
